"""
ZYNORIQ COPILOT™ — PDF Report Service v1.0
Professional PDF generation with i18n, branding, anti-hallucination
"""
import os, json, time, threading, uuid
from datetime import datetime
from zoneinfo import ZoneInfo

try:
    from fpdf import FPDF
except ImportError:
    FPDF = None

# ── i18n ──────────────────────────────────────────────────────────────────
_T = {
    'fr': {
        'generated_by': 'Généré par ZYNORIQ Copilot™',
        'date': 'Date',
        'language': 'Langue',
        'module': 'Module',
        'plan': 'Plan',
        'exec_summary': 'Résumé Exécutif',
        'data_used': 'Données Utilisées',
        'analysis': 'Analyse',
        'confidence': 'Niveau de Confiance',
        'limits': 'Limites de l\'Analyse',
        'recommendations': 'Recommandations',
        'next_action': 'Prochaine Action Recommandée',
        'disclaimer': 'Les analyses de ZYNORIQ sont statistiques et éducatives. Aucun résultat n\'est garanti. Les loteries demeurent des jeux de hasard.',
        'no_data': 'Données insuffisantes pour conclure avec précision.',
        'page': 'Page',
        'of': 'de',
        'report_types': {
            'prediction': 'Rapport de Prédiction',
            'trend': 'Rapport de Tendance',
            'accuracy': 'Rapport Accuracy Score',
            'track_record': 'Rapport Track Record',
            'business': 'Rapport Business AI',
            'project': 'Rapport Projet',
            'strategy': 'Plan Stratégique 30-60-90 Jours',
        },
    },
    'en': {
        'generated_by': 'Generated by ZYNORIQ Copilot™',
        'date': 'Date',
        'language': 'Language',
        'module': 'Module',
        'plan': 'Plan',
        'exec_summary': 'Executive Summary',
        'data_used': 'Data Used',
        'analysis': 'Analysis',
        'confidence': 'Confidence Level',
        'limits': 'Analysis Limitations',
        'recommendations': 'Recommendations',
        'next_action': 'Recommended Next Action',
        'disclaimer': 'ZYNORIQ analyses are statistical and educational. No result is guaranteed. Lotteries remain games of chance.',
        'no_data': 'Insufficient data to conclude with precision.',
        'page': 'Page',
        'of': 'of',
        'report_types': {
            'prediction': 'Prediction Report',
            'trend': 'Trend Report',
            'accuracy': 'Accuracy Score Report',
            'track_record': 'Track Record Report',
            'business': 'Business AI Report',
            'project': 'Project Report',
            'strategy': '30-60-90 Day Strategic Plan',
        },
    },
    'es': {
        'generated_by': 'Generado por ZYNORIQ Copilot™',
        'date': 'Fecha',
        'language': 'Idioma',
        'module': 'Módulo',
        'plan': 'Plan',
        'exec_summary': 'Resumen Ejecutivo',
        'data_used': 'Datos Utilizados',
        'analysis': 'Análisis',
        'confidence': 'Nivel de Confianza',
        'limits': 'Limitaciones del Análisis',
        'recommendations': 'Recomendaciones',
        'next_action': 'Próxima Acción Recomendada',
        'disclaimer': 'Los análisis de ZYNORIQ son estadísticos y educativos. Ningún resultado está garantizado. Las loterías siguen siendo juegos de azar.',
        'no_data': 'Datos insuficientes para concluir con precisión.',
        'page': 'Página',
        'of': 'de',
        'report_types': {
            'prediction': 'Informe de Predicción',
            'trend': 'Informe de Tendencia',
            'accuracy': 'Informe de Accuracy Score',
            'track_record': 'Informe de Track Record',
            'business': 'Informe Business AI',
            'project': 'Informe de Proyecto',
            'strategy': 'Plan Estratégico 30-60-90 Días',
        },
    },
    'pt': {
        'generated_by': 'Gerado por ZYNORIQ Copilot™',
        'date': 'Data',
        'language': 'Idioma',
        'module': 'Módulo',
        'plan': 'Plano',
        'exec_summary': 'Resumo Executivo',
        'data_used': 'Dados Utilizados',
        'analysis': 'Análise',
        'confidence': 'Nível de Confiança',
        'limits': 'Limitações da Análise',
        'recommendations': 'Recomendações',
        'next_action': 'Próxima Ação Recomendada',
        'disclaimer': 'As análises da ZYNORIQ são estatísticas e educativas. Nenhum resultado é garantido. As loterias continuam sendo jogos de azar.',
        'no_data': 'Dados insuficientes para concluir com precisão.',
        'page': 'Página',
        'of': 'de',
        'report_types': {
            'prediction': 'Relatório de Previsão',
            'trend': 'Relatório de Tendência',
            'accuracy': 'Relatório de Accuracy Score',
            'track_record': 'Relatório de Track Record',
            'business': 'Relatório Business AI',
            'project': 'Relatório de Projeto',
            'strategy': 'Plano Estratégico 30-60-90 Dias',
        },
    },
    'ht': {
        'generated_by': 'Jenere pa ZYNORIQ Copilot™',
        'date': 'Dat',
        'language': 'Lang',
        'module': 'Modil',
        'plan': 'Plan',
        'exec_summary': 'Rezime Egzekitif',
        'data_used': 'Done Itilize',
        'analysis': 'Analiz',
        'confidence': 'Nivo Konfyans',
        'limits': 'Limit Analiz la',
        'recommendations': 'Rekòmandasyon',
        'next_action': 'Pwochen Aksyon Rekòmande',
        'disclaimer': 'Analiz ZYNORIQ yo se estatistik ak edikasyon. Pa gen okenn rezilta garanti. Lotri yo rete jwèt aza.',
        'no_data': 'Done ensifizan pou konkli ak presizyon.',
        'page': 'Paj',
        'of': 'nan',
        'report_types': {
            'prediction': 'Rapò Prediksyon',
            'trend': 'Rapò Tandans',
            'accuracy': 'Rapò Accuracy Score',
            'track_record': 'Rapò Track Record',
            'business': 'Rapò Business AI',
            'project': 'Rapò Pwojè',
            'strategy': 'Plan Estratejik 30-60-90 Jou',
        },
    },
}

def t(lang, key):
    return (_T.get(lang) or _T['en']).get(key, _T['en'].get(key, key))

def t_report(lang, report_type):
    types = (_T.get(lang) or _T['en']).get('report_types', {})
    return types.get(report_type, report_type)


# ── Quota ─────────────────────────────────────────────────────────────────
REPORT_QUOTAS = {
    None: 1, "free": 1,
    "pro": 10, "vip": 50,
    "elite": 500, "premium": 50,
    "business": 500, "enterprise": 10000,
}
# File-backed monthly report quotas
_REPORT_USAGE_FILE = os.path.join("data", "copilot_report_usage.json")
_report_usage = {}
_report_lock = threading.Lock()

def _load_report_usage():
    global _report_usage
    try:
        if os.path.exists(_REPORT_USAGE_FILE):
            with open(_REPORT_USAGE_FILE, "r") as f:
                _report_usage = json.load(f)
    except Exception:
        _report_usage = {}

def _save_report_usage():
    try:
        os.makedirs("data", exist_ok=True)
        with open(_REPORT_USAGE_FILE, "w") as f:
            json.dump(_report_usage, f)
    except Exception:
        pass

_load_report_usage()

def check_report_quota(user_id, plan):
    limit = REPORT_QUOTAS.get(plan, 1)
    month = datetime.utcnow().strftime("%Y-%m")
    key = f"{user_id}_{month}"
    with _report_lock:
        count = _report_usage.get(key, 0)
        remaining = max(0, limit - count)
        return remaining > 0, remaining, limit

def consume_report_quota(user_id):
    month = datetime.utcnow().strftime("%Y-%m")
    key = f"{user_id}_{month}"
    with _report_lock:
        _report_usage[key] = _report_usage.get(key, 0) + 1
        _save_report_usage()


# ── Temp file management ─────────────────────────────────────────────────
_REPORT_DIR = os.path.join("data", "reports")
_report_files = {}  # {token: {"path": str, "ts": float, "user_id": int}}
_report_files_lock = threading.Lock()

def _ensure_dir():
    os.makedirs(_REPORT_DIR, exist_ok=True)

def _cleanup_old(max_age_sec=3600):
    now = time.time()
    with _report_files_lock:
        expired = [k for k, v in _report_files.items() if now - v["ts"] > max_age_sec]
        for k in expired:
            try:
                os.remove(_report_files[k]["path"])
            except OSError:
                pass
            del _report_files[k]

def register_file(path, user_id):
    token = uuid.uuid4().hex[:16]
    with _report_files_lock:
        _report_files[token] = {"path": path, "ts": time.time(), "user_id": user_id}
    return token

def get_file(token, user_id):
    _cleanup_old()
    with _report_files_lock:
        entry = _report_files.get(token)
        if not entry:
            return None
        if entry["user_id"] != 0 and entry["user_id"] != user_id:
            return None
        return entry["path"]


# ── PDF Generator ─────────────────────────────────────────────────────────
class ZynoriqPDF(FPDF):
    def __init__(self, lang='fr', report_type='prediction'):
        super().__init__()
        self.lang = lang
        self.report_type = report_type
        self._title_text = t_report(lang, report_type)
        self.set_auto_page_break(auto=True, margin=25)
        # Use built-in fonts with latin encoding
        self.add_page()

    def header(self):
        # Brand bar
        self.set_fill_color(8, 8, 31)
        self.rect(0, 0, 210, 28, 'F')
        # Logo text
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(20, 121, 255)
        self.set_xy(15, 6)
        self.cell(0, 10, 'ZYNORIQ', ln=False)
        # Subtitle
        self.set_font('Helvetica', '', 7)
        self.set_text_color(77, 90, 138)
        self.set_xy(15, 16)
        self.cell(0, 5, 'Intelligence Beyond Prediction')
        # Report type on right
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(255, 215, 0)
        self.set_xy(-80, 10)
        self.cell(65, 8, self._title_text, align='R')
        self.ln(20)

    def footer(self):
        self.set_y(-20)
        # Disclaimer
        self.set_font('Helvetica', 'I', 6)
        self.set_text_color(100, 100, 120)
        disclaimer = t(self.lang, 'disclaimer')
        self.multi_cell(0, 3, disclaimer, align='C')
        # Page number
        self.set_font('Helvetica', '', 7)
        self.set_text_color(77, 90, 138)
        page_text = f"{t(self.lang, 'page')} {self.page_no()}/{{nb}}"
        self.cell(0, 5, page_text, align='C')

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(20, 121, 255)
        self.cell(0, 10, title, ln=True)
        self.set_draw_color(20, 121, 255)
        self.line(self.get_x(), self.get_y(), self.get_x() + 60, self.get_y())
        self.ln(4)

    def body_text(self, text):
        self.set_font('Helvetica', '', 9)
        self.set_text_color(50, 50, 70)
        # Handle markdown-like bold
        clean = text.replace('**', '').replace('*', '').replace('•', '-')
        self.multi_cell(0, 5, clean)
        self.ln(3)

    def key_value(self, key, value):
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(20, 121, 255)
        self.cell(50, 6, f"{key}:", ln=False)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(50, 50, 70)
        self.cell(0, 6, str(value), ln=True)

    def table_row(self, cells, header=False):
        if header:
            self.set_font('Helvetica', 'B', 8)
            self.set_fill_color(20, 20, 50)
            self.set_text_color(255, 255, 255)
        else:
            self.set_font('Helvetica', '', 8)
            self.set_fill_color(245, 245, 250)
            self.set_text_color(50, 50, 70)
        w = 180 / max(len(cells), 1)
        for c in cells:
            self.cell(w, 7, str(c)[:30], border=1, fill=True)
        self.ln()

    def confidence_badge(self, pct):
        if pct >= 85:
            color, label = (34, 232, 122), "TRES FORTE"
        elif pct >= 70:
            color, label = (79, 158, 255), "FORTE"
        elif pct >= 50:
            color, label = (167, 139, 250), "MOYENNE"
        else:
            color, label = (100, 116, 139), "FAIBLE"
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(*color)
        self.cell(0, 8, f"{pct}% - {label}", ln=True)
        self.set_text_color(50, 50, 70)


def generate_report(report_type, lang, data, analysis_text, user_plan=None):
    """Generate a PDF report and return the file path."""
    if FPDF is None:
        return None

    _ensure_dir()
    pdf = ZynoriqPDF(lang=lang, report_type=report_type)
    pdf.alias_nb_pages()
    now = datetime.now(ZoneInfo("America/New_York"))

    # ── Metadata section ──
    pdf.section_title(t_report(lang, report_type))
    pdf.key_value(t(lang, 'date'), now.strftime("%Y-%m-%d %H:%M ET"))
    pdf.key_value(t(lang, 'language'), lang.upper())
    pdf.key_value(t(lang, 'module'), report_type)
    if user_plan:
        pdf.key_value(t(lang, 'plan'), user_plan.upper())

    state = data.get('state', '')
    if state:
        pdf.key_value('State', state)
    game = data.get('game', '')
    if game:
        pdf.key_value('Game', game)
    pdf.ln(5)

    # ── Executive Summary ──
    pdf.section_title(t(lang, 'exec_summary'))
    summary = data.get('summary') or analysis_text[:500] if analysis_text else t(lang, 'no_data')
    pdf.body_text(summary)

    # ── Data Used ──
    pdf.section_title(t(lang, 'data_used'))
    predictions = data.get('predictions', [])
    if predictions:
        pdf.table_row(['#', 'Combo', 'Confidence %', 'Type'], header=True)
        for i, p in enumerate(predictions[:10]):
            combo = p.get('combo', '?')
            conf = p.get('confidence', 0)
            ptype = 'Box 6-way' if len(set(str(combo))) == 3 else 'Box 3-way'
            pdf.table_row([str(i+1), str(combo), f"{conf}%", ptype])
        pdf.ln(3)

    draws = data.get('latest_draws', [])
    if draws:
        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_text_color(20, 121, 255)
        pdf.cell(0, 8, f"Derniers tirages ({len(draws[:10])})", ln=True)
        pdf.table_row(['Date', 'TOD', 'D1', 'D2', 'D3'], header=True)
        for d in draws[:10]:
            pdf.table_row([
                d.get('date', '?'), d.get('tod', ''),
                str(d.get('d1', '')), str(d.get('d2', '')), str(d.get('d3', '')),
            ])
        pdf.ln(3)

    hot = data.get('hot_digits')
    cold = data.get('cold_digits')
    if hot or cold:
        if hot:
            pdf.key_value('Hot Digits', str(hot))
        if cold:
            pdf.key_value('Cold Digits', str(cold))
        pdf.ln(3)

    accuracy = data.get('accuracy')
    if accuracy:
        pdf.key_value('Straight Rate', f"{accuracy.get('straight_rate', '?')}%")
        pdf.key_value('Box Rate', f"{accuracy.get('box_rate', '?')}%")
        pdf.ln(3)

    # ── Analysis ──
    if analysis_text:
        pdf.section_title(t(lang, 'analysis'))
        pdf.body_text(analysis_text)

    # ── Confidence Level ──
    conf_pct = data.get('confidence_pct')
    if conf_pct is not None:
        pdf.section_title(t(lang, 'confidence'))
        pdf.confidence_badge(conf_pct)
        pdf.ln(3)

    # ── Limits ──
    pdf.section_title(t(lang, 'limits'))
    limits = data.get('limits') or t(lang, 'disclaimer')
    pdf.body_text(limits)

    # ── Recommendations ──
    recs = data.get('recommendations')
    if recs:
        pdf.section_title(t(lang, 'recommendations'))
        pdf.body_text(recs)

    next_action = data.get('next_action')
    if next_action:
        pdf.section_title(t(lang, 'next_action'))
        pdf.body_text(next_action)

    # ── Business AI specifics ──
    biz = data.get('business')
    if biz:
        pdf.section_title('Business Intelligence')
        if biz.get('name'):
            pdf.key_value('Project', biz['name'])
        if biz.get('score'):
            pdf.key_value('Score', f"{biz['score']}/100")
        if biz.get('risks'):
            pdf.key_value('Risks', biz['risks'])
        if biz.get('opportunities'):
            pdf.key_value('Opportunities', biz['opportunities'])
        pdf.ln(3)

    # ── Save ──
    filename = f"zynoriq_{report_type}_{state or 'all'}_{now.strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}.pdf"
    filepath = os.path.join(_REPORT_DIR, filename)
    pdf.output(filepath)
    return filepath


# ── Report types available ────────────────────────────────────────────────
REPORT_TYPES = ['prediction', 'trend', 'accuracy', 'track_record', 'business', 'project', 'strategy']
